name: G:\.conda\envs\shrecc
channels:
  - cmutel
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.8.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py39ha55e580_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asteval=1.0.6=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-lru=2.0.4=pyhd8ed1ab_1
  - attrs=24.3.0=pyh71513ae_0
  - babel=2.16.0=pyhd8ed1ab_1
  - beautifulsoup4=4.12.3=pyha770c72_1
  - bleach=6.2.0=pyhd8ed1ab_3
  - bleach-with-css=6.2.0=hd8ed1ab_3
  - blinker=1.9.0=pyhff2d567_0
  - brightway25=1.0.6=py_11
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py39ha51f57c_2
  - brotlicffi=1.1.0.0=py39ha51f57c_2
  - bw2analyzer=0.11.7=py_0
  - bw2calc=2.0=py_0
  - bw2data=4.4.2=pyhd8ed1ab_0
  - bw2io=0.9.6=pyhd8ed1ab_0
  - bw2parameters=1.1.0=pyhd8ed1ab_1
  - bw_migrations=0.2=pyhd8ed1ab_1
  - bw_processing=1.0=pyhd8ed1ab_1
  - bw_simapro_csv=0.2.3=py_0
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.1.31=h56e8100_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.2=h5782bbf_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py39ha55e580_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h2b77a98_2
  - cpython=3.9.21=py39hd8ed1ab_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.12=py39ha51f57c_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - deepdiff=7.0.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.15=pyhd8ed1ab_1
  - double-conversion=3.3.0=h63175ca_0
  - ecoinvent_interface=3.0=py_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.8=py39hf73967f_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=hdaf720e_2
  - frozendict=2.4.6=py39ha55e580_0
  - fsspec=2025.2.0=pyhd8ed1ab_0
  - ftfy=6.3.1=pyhd8ed1ab_1
  - graphite2=1.3.13=h63175ca_1003
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=10.2.0=h885c0d4_0
  - hpack=4.0.0=pyhd8ed1ab_1
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflate64=1.0.1=py39ha55e580_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.18.1=pyh7428d3b_3
  - isodate=0.7.2=pyhd8ed1ab_1
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - json-logging=1.3.0=pyhd8ed1ab_0
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py39hcbf5309_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - jupyter_events=0.11.0=pyhd8ed1ab_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=28_h576b46c_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=28_h7ad3364_mkl
  - libclang13=19.1.7=default_ha5278ca_1
  - libdeflate=1.23=h9062f6e_0
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.2=h8ffe710_5
  - libgcc=14.2.0=h1383e82_1
  - libglib=2.82.2=h7025463_1
  - libgomp=14.2.0=h1383e82_1
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=28_hacfb0e4_mkl
  - liblzma=5.6.3=h2466b09_1
  - libpng=1.6.46=had7236b_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.47.2=h67fdade_0
  - libtiff=4.7.0=h797046b_3
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.5=he286e8c_1
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - line_profiler=4.1.3=py39h2b77a98_1
  - loguru=0.7.2=py39hcbf5309_2
  - lxml=5.3.0=py39hcc8b0fb_2
  - markupsafe=3.0.2=py39hf73967f_1
  - matplotlib=3.9.4=py39hcbf5309_0
  - matplotlib-base=3.9.4=py39h5376392_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - matrix_utils=0.6=py_0
  - mistune=3.1.0=pyhd8ed1ab_0
  - mkl=2024.2.2=h66d3029_15
  - morefs=0.2.0=py_0
  - mrio_common_metadata=0.2.1=py_0
  - multifunctional=0.6=py_0
  - multivolumefile=0.2.3=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.5=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.26.4=py39hddb5d58_0
  - openjpeg=2.5.3=h4d64b90_0
  - openpyxl=3.1.5=py39ha55989b_1
  - openssl=3.4.1=ha4e3fda_0
  - ordered-set=4.1.0=pyhd8ed1ab_1
  - orjson=3.10.15=py39h92a245a_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h2366fc2_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h3d7b363_2
  - peewee=3.17.7=py39hc8732b6_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py39h73ef694_0
  - pint=0.23=pyhd8ed1ab_1
  - pip=24.3.1=pyh8b19718_2
  - pixman=0.44.2=had0cd8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.1=py39ha55e580_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py7zr=0.22.0=pyhd8ed1ab_1
  - pybcj=1.0.3=py39ha55e580_0
  - pycparser=2.22=pyh29332c3_1
  - pycryptodomex=3.21.0=py39ha55e580_0
  - pydantic=2.10.4=pyh3cfb1c2_0
  - pydantic-core=2.27.2=py39h92a245a_0
  - pydantic-settings=2.7.1=pyh3cfb1c2_0
  - pyecospold=4.0.0=py_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pypardiso=0.4.6=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyppmd=1.1.0=py39ha51f57c_1
  - pyside6=6.8.1=py39h0285922_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.9.21=h37870fc_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-dotenv=1.0.1=pyhd8ed1ab_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.9=5_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=307=py39ha51f57c_3
  - pywinpty=2.0.15=py39ha51f57c_0
  - pyxlsb=1.0.10=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39hf73967f_2
  - pyzmq=26.2.1=py39h03e5c00_0
  - pyzstd=0.16.2=py39h9bf74da_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.8.1=h1259614_2
  - randonneur=0.6.1=pyhd8ed1ab_0
  - randonneur_data=0.5.4=pyhd8ed1ab_0
  - rapidfuzz=1.4.1=py39h690af90_0
  - rdflib=7.1.1=pyhd8ed1ab_1
  - referencing=0.35.1=pyhd8ed1ab_1
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.22.3=py39h92a245a_0
  - scipy=1.13.1=py39h1a10956_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=75.6.0=pyhff2d567_1
  - setuptools-scm=8.1.0=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - snakeviz=2.2.2=pyhd8ed1ab_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snowflake-id=1.0.2=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sparqlwrapper=2.0.0=pyha770c72_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - stats_arrays=0.6.5=py_2
  - statsmodels=0.14.4=py39h4b0a98a_0
  - structlog=24.4.0=pyhd8ed1ab_1
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2021.13.0=h62715c5_1
  - terminado=0.18.1=pyh5737063_0
  - texttable=1.7.0=pyhd8ed1ab_1
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py39ha55e580_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2024b=hc8b5060_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py39ha55e580_0
  - unidecode=1.3.8=pyh29332c3_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - vc=14.3=ha32ba9b_23
  - vc14_runtime=14.42.34433=he29a5d6_23
  - voluptuous=0.15.2=pyhd8ed1ab_2
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win32_setctime=1.2.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.2=py39ha55e580_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xlsxwriter=3.2.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=ha9f60a1_7
  - zipfile-deflate64=0.2.0=py39ha55989b_4
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py39h9bf74da_1
  - zstd=1.5.6=h0ea2cb4_0
prefix: G:\.conda\envs\shrecc
